### ISSUE TITLE
Metacello loading script error in Pharo 7.0.4

### ISSUE THREAD

**Issue by juliangrigera** [woden-engine/woden#18]
When running the Metacello script on a fresh 64b Pharo 7.0.4

``` 
Metacello new
  baseline: 'WodenEngine';
  repository: 'github://woden-engine/woden/tonel';
   load
```
The following exception arises:
"LowtalkSLVMObjectModel(Object)>>doesNotUnderstand: #falseLiteralValue"
Stack attached.
[Debugger-Stack-LowtalkSLVMObjectModel-2020-01-07-102113.fuel.zip](https://github.com/woden-engine/woden/files/4030841/Debugger-Stack-LowtalkSLVMObjectModel-2020-01-07-102113.fuel.zip)

**Comment by ronsaldo** [comment]
I just reverted that change, so it should be possible to load it in a clean image. I just tested on my linux desktop. You may need to remove pharo-loca directory so that the dependency is reloaded.

**Comment by juliangrigera** [comment]
Nice, loads perfectly now!
