### ISSUE TITLE
Running any sample results in an exception

### ISSUE THREAD

**Issue by psvensson** [woden-engine/woden#19]
I'm running on a Linux Mint 20;  5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I get he following exception; 
![image](https://user-images.githubusercontent.com/39554/91990331-e33fa180-ed31-11ea-880e-c366d3b2e946.png)

This looks really promising ti would be nice to get it running. I there anything in particular I can do?

**Comment by psvensson** [comment]
I also just checked that my graphics card support OpenGL 4.6;

----------------------------------------

OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1070/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 440.95.01
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 440.95.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 440.95.01
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Comment by ronsaldo** [comment]
That is bug that I introduced when working on a dependency. I just fixed it, so you need to reload the following two dependencies from Iceberg:
- slovim
- dastrel

You may need to reset the engine instance by doing *WDCEngine reset* in playground.

**Comment by psvensson** [comment]
Hi Ronsaldo, thank you for the quick fix! It works!
