### ISSUE TITLE
What *is* woden2 - World Dynamic Engine 2?

### ISSUE THREAD

**Issue by rjsargent** [woden-engine/woden#2]
The README.md document doesn't address one word toward answering what woden2 actually is.
Google search for World Dynamic Engine finds results about variable fuel economy in petroleum powered engines.

Please add a paragraph summarizing what it is, etc.
(apologies for such a nattering issue)

**Comment by MarcusDenker** [comment]
This seems to be fixed, it now states on the readme page:

World Dynamic Engine - A 3D graphics engine for Pharo
