### ISSUE TITLE
Failed to open the AGPU device

### ISSUE THREAD

**Issue by wgerbert** [woden-engine/woden#20]
In a clean Pharo 9 Image on Windows 10 I installed woden:
`Metacello new
   baseline: 'WodenEngine';
   repository: 'github://woden-engine/woden/tonel';
   load`
 and than tried the given example:
`|model|
model := WDAModel new.
model openWith: (WDASolidColorViewSample new color: Color blue)`
I get the following error:
![image](https://user-images.githubusercontent.com/70092519/96481319-ab39e280-123b-11eb-828f-824b3ed7a0b3.png)

**Comment by ronsaldo** [comment]
What is the graphics card on your machine? Woden requires Vulkan to work.

**Comment by wgerbert** [comment]
My graphic card is a **NVIDIA GeForce GT 525M** .
I installed the corresponding Vulkan Driver from the NVIDIA Page and the error disappeared. Thank you!
