### ISSUE TITLE
Unable to find 'RWNode' when installing in fresh Pharo 9

### ISSUE THREAD

**Issue by psvensson** [woden-engine/woden#21]
Hi, I just created a new (development) Pharo 9 image and tried to install Woden using the suggested method, and after a while I got the following error;

![image](https://user-images.githubusercontent.com/39554/111441166-5b3a4b80-8707-11eb-954d-077987f8cdc9.png)

Is there something missing from the baseline maybe?

**Comment by psvensson** [comment]
However, when I clicked 'Proceed' just to see what happened, the rest of the installation went fine. Strange, but OK

**Comment by ronsaldo** [comment]
I have just pushed the latest version onto this repository. Try loading it again on a clean image.

**Comment by psvensson** [comment]
Thanks! I was now able to load everything fine without a hitch
