### ISSUE TITLE
Instance of WMWorldRenderer does not udnerstand #scaleFactor when opening editor form menu

### ISSUE THREAD

**Issue by psvensson** [woden-engine/woden#22]
Using fresh install of Pharo 9 and trying to open editor first thing after installation.
![image](https://user-images.githubusercontent.com/39554/111475479-6902c780-872d-11eb-8196-95cb543c020b.png)

**Comment by ronsaldo** [comment]
I have just pushed the latest version onto this repository. Try loading it again on a clean image.

**Comment by psvensson** [comment]
I do not get this error anymore, but instead the image hangs silently when trying the menu item Library -> Woden -> Open level editor.

I tried this the first thing I did, and then I killed the image and started again by instead loading a Roassal example (which looks really great, by the way!), and then trying the editor again, but the same thing happened again. All other examples I've tried also work (the fox, the gallery, et.c.)

**Comment by ronsaldo** [comment]
Weird, what is your OS and your graphics card? on my desktop machine with Ubuntu 20.10, AMD Vega 64 this is just working on a fresh image. Also, Pharo 9 for this latest version is required. 

Apart from that, the level editor is still on an early stage, and I still have to define the interface for looking up materials for a specific project or game. Also, in the long term I am planning on making a new much simpler version of Woden with better Spec and Inspector integration.

**Comment by psvensson** [comment]
I am using Linux Mint 20 and the following Graphics card:
-----
Graphics:  Device-1: NVIDIA GP104 [GeForce GTX 1070] driver: nvidia v: 450.102.04 
           Display: x11 server: X.Org 1.20.9 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 3840x2160~60Hz 
           OpenGL: renderer: GeForce GTX 1070/PCIe/SSE2 v: 4.6.0 NVIDIA 450.102.04
-----

I didn't know it was a work in progress, I was just looking to try out different things. I can return to try it out later instead.

Currently I have succeeded in importing my own models (after finding the correct directory in the local git clone) and it works very well. Also, the code needed is really lightweight and very readable. I've been using three.js from time to time before and Woden feels like 10x less code for the same result, just from an API level (or perhaps it is a language level also :) )
