### ISSUE TITLE
Building on Windows not requiring Powershell

### ISSUE THREAD

**Issue by philippeback** [woden-engine/woden#3]
If one wants to build on Windows, there could be options:

1. Use WSL when on Windows 10
2. Use something like Babun to have a better cygwin and there is the pact package manager (an apt-get like thing). This can help in building lots of things.

I will try out the build under WSL.

**Comment by ronsaldo** [comment]
Manually building dependencies is no longer required. These dependencies are being build automatically on Travis and Appveyor, and now they are fetched after baseline loading.
