### ISSUE TITLE
New error loading woden in mac

### ISSUE THREAD

**Issue by akevalion** [woden-engine/woden#4]
Mac OS - 10.13.4

You will need `python` and `wget` in your system with `brew`

After loading

1. Open pharo-gui
2. select woden.image
3. run the next script

```Smalltalk
model := WDAModel new.
model openWith: (WDASolidColorViewSample new color: Color blue)
```
4. An errror appears ExternalModule Not found

**Comment by ronsaldo** [comment]
Python and wget is no longer required.
